version: '3'
services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: training_r1
  web:
    build: ./portal
    ports:
     - "3000:3000"
    # volumes:
    #   - .:/portal
    depends_on:
      - db
