version: '3'
services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  web:
    build: ./portal
    ports:
     - "3000:3000"
    # volumes:
    #   - .:/portal
    depends_on:
      - db
